<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="deliverbot">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="base_mass" value="0.3" /> <!-- arbitrary value for base mass -->
  <xacro:property name="base_width" value="0.1" />
  <xacro:property name="base_length" value="0.1" />
  <xacro:property name="base_height" value="0.05" />
  <xacro:property name="wheel_mass" value="0.3" /> <!-- arbitrary value for wheel mass -->
  <xacro:property name="wheel_len" value="0.020" />
  <xacro:property name="wheel_radius" value="0.015" />
  <xacro:property name="z_offset" value="-${base_height/2}" /> <!-- Space btw top of beam and the each joint -->

  <link
    name="base_link">
    <inertial>
      <origin
        xyz="-0.0054933 -4.1587E-05 0.062041"
        rpy="0 0 0" />
      <mass
        value="0.43668" />
      <inertia
        ixx="0.0029446"
        ixy="-1.0694E-05"
        ixz="8.6442E-05"
        iyy="0.0086395"
        iyz="-7.9718E-07"
        izz="0.0097467" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://deliverbot_description/meshes/LingFeng/LingFeng_base.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 0.812 0 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://deliverbot_description/meshes/LingFeng/LingFeng_base.STL" />
      </geometry>
    </collision>
  </link>
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <parent link="base_footprint"/>
    <child link="base_link"/>
  </joint>

  <link
    name="wheel_la_link">
    <inertial>
      <origin
        xyz="-7.128E-08 -0.024133 -1.2354E-07"
        rpy="0 0 0" />
      <mass
        value="0.72164" />
      <inertia
        ixx="0.0014337"
        ixy="-1.4592E-09"
        ixz="1.906E-10"
        iyy="0.0026176"
        iyz="-2.5284E-09"
        izz="0.0014337" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://deliverbot_description/meshes/LingFeng/wheel_left.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.2 0.2 0.2 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://deliverbot_description/meshes/LingFeng/wheel_left.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="wheel_la_joint"
    type="continuous">
    <origin
      xyz="0.12 0.1595 0.02"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="wheel_la_link" />
    <axis
      xyz="0 1 0" rpy="0 0 0" />
  </joint>
  <link
    name="wheel_lb_link">
    <inertial>
      <origin
        xyz="-7.128E-08 -0.024133 -1.2354E-07"
        rpy="0 0 0" />
      <mass
        value="0.72164" />
      <inertia
        ixx="0.0014337"
        ixy="-1.4592E-09"
        ixz="1.906E-10"
        iyy="0.0026176"
        iyz="-2.5284E-09"
        izz="0.0014337" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://deliverbot_description/meshes/LingFeng/wheel_left.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.2 0.2 0.2 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://deliverbot_description/meshes/LingFeng/wheel_left.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="wheel_lb_joint"
    type="continuous">
    <origin
      xyz="-0.12 0.1595 0.02"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="wheel_lb_link" />
    <axis
      xyz="0 1 0" rpy="0 0 0" />
  </joint>
  <link
    name="wheel_ra_link">
    <inertial>
      <origin
        xyz="-7.1345E-08 0.024133 -1.235E-07"
        rpy="0 0 0" />
      <mass
        value="0.72164" />
      <inertia
        ixx="0.0014337"
        ixy="1.4601E-09"
        ixz="1.9073E-10"
        iyy="0.0026176"
        iyz="2.5279E-09"
        izz="0.0014337" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://deliverbot_description/meshes/LingFeng/wheel_right.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.2 0.2 0.2 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://deliverbot_description/meshes/LingFeng/wheel_right.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="wheel_ra_joint"
    type="continuous">
    <origin
      xyz="0.12 -0.1595 0.02"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="wheel_ra_link" />
    <axis
      xyz="0 1 0" rpy="0 0 0" />
  </joint>
  <link
    name="wheel_rb_link">
    <inertial>
      <origin
        xyz="-7.128E-08 -0.024133 -1.2354E-07"
        rpy="0 0 0" />
      <mass
        value="0.72164" />
      <inertia
      ixx="0.0014337"
      ixy="-1.4592E-09"
      ixz="1.906E-10"
      iyy="0.0026176"
      iyz="-2.5284E-09"
      izz="0.0014337" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://deliverbot_description/meshes/LingFeng/wheel_right.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.2 0.2 0.2 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://deliverbot_description/meshes/LingFeng/wheel_right.STL" />
      </geometry>
    </collision>
  </link>
  <joint
    name="wheel_rb_joint"
    type="continuous">
    <origin
      xyz="-0.12 -0.1595 0.02"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="wheel_rb_link" />
    <axis
      xyz="0 1 0" rpy="0 0 0" />
  </joint>
  </xacro:macro>

</robot>
